name: "WordPress Base Project Build and Deploy"

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node Version required Build script"
        type: string
        required: false
        default: 18

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Building Project
        run: |
          if [[ -f ./scripts/create-build ]]
          then 
            ./scripts/create-build
          else
            echo "No build script provided"
            exit 1
          fi

          if [[ ! -d ./build ]]
          then
            echo "'build' folder is expected after running 'build' script"
            exit 1
          fi
        shell: bash
      - name: Archive build folder
        uses: actions/upload-artifact@v3
        with:
          name: project-build
          path: build
  deploy-dev:
    name: Deploy to Production
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch archived build folder
        uses: actions/download-artifact@v3
        with:
          name: project-build
      - run: ls -R
  deploy-prod:
    name: Deploy to Development
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch archived build folder
        uses: actions/download-artifact@v3
        with:
          name: project-build
      - run: ls -R
